### ISSUE TITLE
npm ERR! Error: unauthorized Name or password is incorrect.: express

### ISSUE THREAD

**Issue by tj** [terinjokes/docker-npmjs#11]
can't seem to get anything installing, I'll look into it but there might be something we should add to the docs, or if you know what this is that works too :D

**Comment by terinjokes** [comment]
Hey TJ.

If you move your .npmrc out of the way does it work? npm likes sending authentication with every request, even if its not needed.

If so, i'll update the documentation. Running `npm adduser` and just hitting enter should setup the delegate to use the same auth.

**Comment by tj** [comment]
interesting yeah moving my .npmrc fixed it!

**Comment by tj** [comment]
oh wait no haha that's just going to the regular npm duh, my bad, I'm using nom-delegate. It does seem to proxy correctly now though

**Comment by tj** [comment]
one thing I was wondering is if we can maybe come up with a way to make sure that packages marked as `private` can be accepted by this npm so that we can be sure no one accidentally published to npmjs.org haha

**Comment by domenic** [comment]
You should be able to use publishConfig to ensure packages can only be published to certain registries.

**Comment by terinjokes** [comment]
So, to clarify, moving npmrc out of the way does not fix the the issue? 

If so, this is new to me, but will look at it.

**Comment by tj** [comment]
@domenic ah! cool I'll look into that

@terinjokes nope it does, thanks!

**Comment by junosuarez** [comment]
@visionmedia, to elaborate on @domenic's post, packages targeted at a particular (i.e., private) npm registry should have their `registry` property set to the url of that registry: https://npmjs.org/doc/misc/npm-config.html#registry

**Comment by domenic** [comment]
@jden I think that's just the command line option; I was referring to `publishConfig` at https://npmjs.org/doc/json.html#publishConfig

**Comment by junosuarez** [comment]
@domenic we're referring to the same thing :) quoth the `npm-config` docs (top of the page I linked to above):

> npm gets its configuration values from 6 sources, in this priority:

One of which is the optional `publishConfig` property in a `package.json` file.
