### ISSUE TITLE
can't assign host to an ip

### ISSUE THREAD

**Issue by tj** [terinjokes/docker-npmjs#14]
docker freaks out if you use -h:

```
2013/12/02 20:29:41 Error: create: ExportEnv json: cannot unmarshal number into Go value of type string
```

I've tried -e HOSTNAME=ip but no dice, maybe we should use a different env var? I tried changing that myself but it seems to confuse kappa, digging into kappa now

**Comment by terinjokes** [comment]
-h requires a hostname, that's all i'm going to support at this time.

**Comment by terinjokes** [comment]
The reason is because the delegate needs a route to connect to, and using IP addresses gets really flakey really quickly. I can't rely on the user being on a network that correctly hairpins IP addresses, and it's way simplier to have a hostname that resolves to localhost within the container and to the host for the rest of the network.

**Comment by tj** [comment]
yeah bit of an edge-case, I didn't want to bother but might as well

**Comment by tj** [comment]
I guess the thing for me is I want to run it as registry.segment.io, but then kappa can't respond with the proper host for npm to fetch from, but looks like kappa has a .vhost option! just need to tweak the build. It would be nice to have `-e HOST=registry.segment.io` or similar for that

**Comment by terinjokes** [comment]
We run the service internally as `docker run -d -h npmjs.cloudflare.internal -p=5984:5984 -p=1337:1337 npmjs`.

The "real" registry is npmjs.cloudflare.internal:5984, with the delegated repository at npmjs.cloudflare.internal:1337. Setting up the host is already done for you.

**Comment by terinjokes** [comment]
I've updated the documentation in the README to make this more clear.
