### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by LoicMahieu** [terinjokes/docker-npmjs#20]
During NPM install, `./load-views.sh` has been run and `unexpected EOF` is thrown.
I don't understand anything about what causes this, so I post it here.

To fully understand, here all the logs: https://gist.github.com/LoicMahieu/f33386eef799914e4348

Thanks.

**Comment by terinjokes** [comment]
I'm not able to reproduce this. Where are you running the docker?

**Comment by Fridus** [comment]
I had the same problem.
This problem is on Vagrant(1.4.3) on Mac OSX(10.9.1): http://docs.docker.io/en/latest/installation/vagrant/
I've fixed this bug in my pull request #21.

**Comment by terinjokes** [comment]
I released v0.5.2, can you see if this is still an issue?
