### ISSUE TITLE
Create Migration Notes

### ISSUE THREAD

**Issue by Bockit** [terinjokes/docker-npmjs#23]
I have a registry we've been running for a few months now (pre-kappa) and I'd like to update the image.

I was wondering if there are any recommendations on how I should go about this.

**Comment by terinjokes** [comment]
@Bockit Awesome to hear that people were using it, even back then!

On the current develop branch I'm recommending storing the CouchDB registries outside the container. Unfortunately this was not the recommendation on the older, or even current master, versions. :(

I'm going to spin up an older container and write up migration notes.

**Comment by Bockit** [comment]
Yeah that's fine. I remember at the time there was an issue about splitting it into 2 containers, but nothing was resolved at the time iirc.

Anything you could suggest would be great. At the moment I have a fallback plan of writing a script to download all versions of all packages we have on there and publishing to a new registry. As far as I can tell we'll lose some metadata and will have to add maintainers again but that's not a big problem.

**Comment by terinjokes** [comment]
I haven't written up the steps yet, but if you want to experiment at your own risk (which is silly, because you made a copy before getting started), it's pretty straightforward.
- Attach to your currently running image and scp or rsync out the databases. Probably located at `/var/lib/couchdb/`.
- Bring up a docker-npmjs following the instructions on the `couchdb` branch.
- Stop the container and copy in the databases to the folder on the host.

You should be good to go at this point. You might want to push the new design docs and views, but we should handle this automatically going forward.

**Comment by Bockit** [comment]
Thanks, I'll try it out this week.

Yep, backups :)

**Comment by terinjokes** [comment]
@Bockit: any update on if this was successful?

**Comment by Bockit** [comment]
@terinjokes sorry for the delay.

I finally got around to trying this yesterday afternoon. I was able to get the couchdb databases out, but I'm having issues running the new docker image. I'm using the couchdb branch instructions.

First issue, the readme says to use `terinjokes/docker-npmjs` which seems to be a 404 on the registry, so I've been using terinjokes/npmjs instead.

Second issue, running the image gives me the following error every time:

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
No SSH host key available. Generating one...
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
*** Running /etc/my_init.d/50_enforce_couchdb_permissions.sh...
*** /etc/my_init.d/50_enforce_couchdb_permissions.sh failed with exit code 32512

*** Killing all processes...
```

I've tried the following commands:

`sudo docker run -v /var/couch/couchdb:/opt/couchdb/var/lib/couchdb/:rw terinjokes/npmjs`
`sudo docker run -v /home/ec2-user/couchdb:/opt/couchdb/var/lib/couchdb/:rw terinjokes/npmjs`
`sudo docker run terinjokes/npmjs`

In all cases I get the same error.

**Comment by Bockit** [comment]
I really don't know if this is the case, but a bit of searching yielded [this possibility](https://www.ruby-forum.com/topic/49024), that a shebang might be missing from the script in question. Looking at the docker-couchdb repository I see that it doesn't have the shebang in [`50_enforce_couchdb_permissions.sh`](https://github.com/terinjokes/docker-couchdb/blob/master/build/50_enforce_couchdb_permissions.sh), whereas the docker-npmjs [`51_configure_npmjs.sh`](https://github.com/terinjokes/docker-npmjs/blob/couchdb/build/51_configure_npmjs.sh) script does.

Do you think that might be the issue?

**Comment by terinjokes** [comment]
That's probably the cause of the issue. But I need to update master here to one of the docker-couchdb branches.

**Comment by Bockit** [comment]
@terinjokes I was wondering if there's anything I can do to work around this bug and create the updated docker container based on the couchdb branch.

**Comment by terinjokes** [comment]
This is at the top of the task list.

**Comment by terinjokes** [comment]
I just pushed updated versions of docker-couchdb and the couchdb branch of docker-npmjs. (There's also initial support for the delegate/kappa setup over at docker-npmjs-deleage)

Adding support for vhosts is next on my list.

**Comment by Bockit** [comment]
Thanks @terinjokes, I'll try the migration again over the weekend.

**Comment by Bockit** [comment]
Hmm, I still have the same problem:

```
$ docker pull terinjokes/npmjs
Pulling repository terinjokes/npmjs
34db14e38166: Pulling dependent layers 
511136ea3c5a: Download complete 
34db14e38166: Download complete 
9cd978db300e: Download complete 
83da74670f8f: Download complete 
b4d20668744e: Download complete 
c9c0e86c5700: Download complete 
9630cea817e9: Download complete 
0ec2263b38de: Download complete 
83bc4d21347b: Download complete 
b093ead02bf9: Download complete 
4d6e1d7ac16a: Download complete 
ccf4fbd7d9f2: Download complete 
af6d8c56d50a: Download complete 
4885953ae9dd: Download complete 
8fe1a5d058d5: Download complete 
53dc33c48b8b: Download complete 
d23fcae5d4fa: Download complete 
7a2188065059: Download complete 
98c1433eb969: Download complete 
e6efeb703b64: Download complete 
4b5cafd5d19f: Download complete 
9ad241aaa383: Download complete 
6459f8b3ba48: Download complete 
5ac77c136b91: Download complete 
1ea01a42a0e9: Download complete 

$ docker run terinjokes/npmjs
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
No SSH host key available. Generating one...
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
*** Running /etc/my_init.d/50_enforce_couchdb_permissions.sh...
*** /etc/my_init.d/50_enforce_couchdb_permissions.sh failed with exit code 32512

*** Killing all processes...
```

**Comment by terinjokes** [comment]
Install by pulling the branch, I haven't tagged a new release.
