### ISSUE TITLE
Split into two images?

### ISSUE THREAD

**Issue by terinjokes** [terinjokes/docker-npmjs#3]
Would people prefer that this live in two containers? For example, one for npmjs and one for npm-delegate? Or do people like the integrated approach I went with originally here?

**Comment by Raynos** [comment]
If this works out of the box as is, it is amazing.

Having tried setting up private npm a bunch of times before its painfully difficult to do.

Maybe support both if you think there is value in it?

**Comment by terinjokes** [comment]
It should work out of the box as is, we're using it internally here, it and seems a bunch of people elsewhere are as well. If it doesn't, that's an issue ;)

I think I might hold off deciding just a tad to see the direction that Docker (and community) is going with regard to networking

**Comment by terinjokes** [comment]
I think with the `link` functionality added in Docker 0.6.5, it looks clearer and clearer that npm-delegate should exist somewhere else.

**Comment by jasisk** [comment]
I think it's worth it, particularly in preparation for 0.8.
[This issue](https://github.com/dotcloud/docker/issues/1352) is scheduled for that release and is for spinning up multiple containers from a single dockerfile.

**Comment by terinjokes** [comment]
I've decided to wait to see what options well get as we progress to 1.0
